### ISSUE TITLE
Support drm?

### ISSUE THREAD

**Issue by sabitahmad** [Taipoon/NeoUdeler#2]
How to download drm protected videos?

**Comment by Taipoon** [comment]
@sabitahmad 
We have not encountered any DRM-protected video downloads on Udemy. However, we have also heard that Udemy is starting to provide DRM protection for many videos. If you are experiencing problems with DRM-protected videos, can you describe the specific situation?

**Comment by sabitahmad** [comment]
$ python3 main.py
Traceback (most recent call last):
  File "/workspaces/NeoUdeler/main.py", line 5, in <module>
    from neoudeler import UdemyDownloader
  File "/workspaces/NeoUdeler/neoudeler.py", line 72, in <module>
    class VideoFormat(enum.StrEnum):
AttributeError: module 'enum' has no attribute 'StrEnum'



Facing this error

**Comment by Taipoon** [comment]
@sabitahmad 
Thank you. To me, that error looks like you're running a version of Python where the `enum` module doesn't have `StrEnum`. To run this code correctly, you need Python 3.10 or later. So, please check your Python runtime environment with the following command:
`$ python3 --version`

If it's 3.9 or lower, you'll need to upgrade your Python to 3.10 or higher. Also, this error has nothing to do with issues supporting DRM-protected videos.

**Comment by sabitahmad** [comment]
The problem is solved. It's not running in version 3.10 also. It needs 3.11
minimum make sure to mention that in readme.
